### ISSUE TITLE
Reading a JSON Cookie

### ISSUE THREAD

**Issue by siebird** [khalwat/cookies#5]
I'm not sure if this is possible. Can this plugin read a JSON cookie set with Javascript? Using this  [JavaScript Cookie](https://github.com/js-cookie/js-cookie#json) plugin to set a cookie from a JSON object. Looks like it converts to a string for storage:

`{%22airbrush%22:1%2C%22doorView%22:%22_straight_%22%2C%22handle%22:%22handle%22%2C%22modelName%22:%22Galveston%20Left%22%2C%22modelNum%22:%22NL-2010%22%2C%22msrp%22:435%2C%22colorName%22:%22Bronze%22%2C%22colorValue%22:%22br%22%2C%22scene%22:%22rancher%22%2C%22sister%22:%22NR-2010%22%2C%22swatches%22:[%22wh%22%2C%22iv%22%2C%22sa%22%2C%22cl%22%2C%22br%22]}`

I'm able to see the raw data, but I can't decode it. `{% set cookieVisualizer = getCookie('pca_dvSavedState') %}`.

**Comment by khalwat** [comment]
So it will read whatever the cookie is set to; but if it's in JSON format, it'll be up to you to then decode it. Cookies are just text.
